     #!/bin/bash

 Update the system
echo "[TASK 1] Updating the system"
yum update -y >/dev/null 2>&1

# Install desired packages
echo "[TASK 2] Installing desired packages"
yum install -y -q vim redhat-lsb-core net-tools bind-utils >/dev/null 2>&1

# Set up global aliases and exports
echo "[TASK 3] Creating global aliases and functions"
cat >>/etc/bashrc <<EOF
# Generated by Vagrant
alias vi='vim'
alias sudo='sudo '
export EDITOR=vim
export TERM=xterm
# Generated by Vagrant
EOF

echo "colorscheme elflord" >> /etc/vimrc

# Enable password authentication
echo "[TASK 4] Enabling password authentication in sshd config"
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd

# Disable SELinux
echo "[TASK 5] Disable SELinux"
setenforce 0
sed -i --follow-symlinks 's/^SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

# Set Root password
echo "[TASK 6] Set root password"
echo "admin" | passwd --stdi                                                   n root >/dev/null 2>&1

# Disable and stop firewalld
echo "[TASK 7] Disable and stop firewalld"
systemctl disable firewalld >/dev/null 2>&1
systemctl stop firewalld

# Update hosts file
echo "[TASK 8] Update /etc/hosts file"
cat >>/etc/hosts<<EOF
10.10.10.4	jmaster.ops.raindrop.best	jmaster 
10.10.10.5  jworker.ops.raindrop.best   jworker
10.10.11.4  grafana.ops.raindrop.best	grafana
10.10.12.4	zabbix.ops.raindrop.best    zabbix
10.10.13.4  jump.ops.raindrop.best      jump
10.10.14.4  elk.ops.raindrop.best       elk
EOF

#Restart VM
reboot now